version: '3.9'

volumes:
  fhir-store-data:

services:
  spark-fhir-store:
    image: sparkfhir/spark:r4-latest
    environment:
      - StoreSettings__ConnectionString=mongodb://root:CosmicTopSecret@mongodb:27017/spark?authSource=admin
      - SparkSettings__Endpoint=http://0.0.0.0:5560/fhir
    ports:
      - "5560:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CosmicTopSecret
    ports:
      - "17017:27017"
    volumes:
      - fhir-store-data:/data/db

